/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Click } from "./Click";
import { ClickCountArgs } from "./ClickCountArgs";
import { ClickFindManyArgs } from "./ClickFindManyArgs";
import { ClickFindUniqueArgs } from "./ClickFindUniqueArgs";
import { DeleteClickArgs } from "./DeleteClickArgs";
import { ClickService } from "../click.service";
@graphql.Resolver(() => Click)
export class ClickResolverBase {
  constructor(protected readonly service: ClickService) {}

  async _clicksMeta(
    @graphql.Args() args: ClickCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Click])
  async clicks(@graphql.Args() args: ClickFindManyArgs): Promise<Click[]> {
    return this.service.clicks(args);
  }

  @graphql.Query(() => Click, { nullable: true })
  async click(
    @graphql.Args() args: ClickFindUniqueArgs
  ): Promise<Click | null> {
    const result = await this.service.click(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Click)
  async deleteClick(
    @graphql.Args() args: DeleteClickArgs
  ): Promise<Click | null> {
    try {
      return await this.service.deleteClick(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
